[package]
name = "stelaro"
version = "0.1.0"
edition = "2021"

[lib]
name = "stelaro_rs"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.5.2"
pyo3 = "0.22.0"

[build-dependencies]
pyo3-build-config = "0.18.2"
