[package]
name = "stelaro"
version = "0.1.0"
edition = "2021"

[lib]
name = "stelaro"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.22.0"
ndarray = "0.16.0"
numpy = "0.22"
rayon = "1.5.2"

[build-dependencies]
pyo3-build-config = "0.22.4"

[features]
extension-module = ["pyo3/extension-module"]
