[package]
name = "stelaro"
version = "0.1.0"
edition = "2021"

[lib]
name = "stelaro"
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0.30"
ndarray-npy = { version = "0.8.1", default-features = false }
rayon = "1.5.2"
pyo3 = { version = "0.22.4", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.22.4"
